server:
  database_uri: ""
  # base_url: "http://localhost:8181/api/"
  # username: "admin"
  # password: "district"
  base_url: "https://hmis-tests.health.go.ug/api/"
  username: "gc.sekiwere"
  password: "123Congse@"
  auth_method: "Basic"
  auth_token: "123456"
