package metadata

import "github.com/spf13/cobra"

var resource string
var MetaDataCmd = &cobra.Command{
	Use:   "metadata",
	Short: "Manage metadata",
}
var KnownResources = []string{
	"aggregateDataExchanges",
	"analyticsTableHooks",
	"apiToken",
	"attributes",
	"categories",
	"categoryCombos",
	"categoryOptionCombos",
	"categoryOptionGroupSets",
	"categoryOptionGroups",
	"categoryOptions",
	"constants",
	"dashboardItems",
	"dashboards",
	"dataApprovalLevels",
	"dataApprovalWorkflows",
	"dataElementGroupSets",
	"dataElementGroups",
	"dataElementOperands",
	"dataElements",
	"dataEntryForms",
	"dataSetNotificationTemplates",
	"dataSets",
	"dataStore",
	"documents",
	"eventCharts",
	"eventFilters",
	"eventReports",
	"eventVisualizations",
	"externalFileResources",
	"externalMapLayers",
	"fileResources",
	"icons",
	"indicatorGroupSets",
	"indicatorGroups",
	"indicatorTypes",
	"indicators",
	"interpretations",
	"jobConfigurations",
	"legendSets",
	"mapViews",
	"maps",
	"me",
	"messageConversations",
	"metadataVersions",
	"minMaxDataElements",
	"oAuth2Clients",
	"optionGroupSets",
	"optionGroups",
	"optionSets",
	"options",
	"organisationUnitGroupSets",
	"organisationUnitGroups",
	"organisationUnitLevels",
	"organisationUnits",
	"predictorGroups",
	"predictors",
	"programDataElements",
	"programIndicatorGroups",
	"programIndicators",
	"programNotificationTemplates",
	"programRuleActions",
	"programRuleVariables",
	"programRules",
	"programSections",
	"programStageSections",
	"programStages",
	"programTrackedEntityAttributeGroups",
	"programs",
	"proposals",
	"pushAnalysis",
	"relationshipTypes",
	"relationships",
	"reports",
	"routes",
	"sections",
	"smsCommands",
	"sqlViews",
	"systemSettings",
	"trackedEntityAttributes",
	"trackedEntityInstanceFilters",
	"trackedEntityTypes",
	"userGroups",
	"userRoles",
	"users",
	"validationNotificationTemplates",
	"validationResults",
	"validationRuleGroups",
	"validationRules",
	"visualizations",
}

func init() {
	// MetaDataCmd.Flags().StringVarP(&resource, "resource", "r", "", "The metadata resource")
	MetaDataCmd.AddCommand(ListCmd)
	MetaDataCmd.AddCommand(ViewResourcesCmd)
	MetaDataCmd.AddCommand(IdentityCmd)
	MetaDataCmd.AddCommand(ValidateCmd)
}
